#!/usr/bin/env bash
# Auto-generated by hyperloom — enablement fix replay script.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
export MODEL=/mnt/kioxia-cm6-3t8/ai/models/ornith-ai/Ornith-1.5-397B-FP8
export TP=8
export MAX_MODEL_LEN=6144
export GPU_TYPE=mi250x
export FRAMEWORK_ROOT=/opt/envs/vllm/lib/python3.12/site-packages

apply_patch() {
  local patch_file="$SCRIPT_DIR/$1"
  for lvl in 1 0 2 3 4 5 6 7 8; do
    if git -C "$FRAMEWORK_ROOT" apply --check -p"$lvl" "$patch_file" 2>/dev/null; then
      git -C "$FRAMEWORK_ROOT" apply -p"$lvl" "$patch_file"
      return 0
    fi
  done
  echo "ERROR: could not apply $patch_file at any strip level" >&2
  return 1
}

apply_patch patches/001_001_gfx90a_fp8_w8a8_bf16_emulation.patch

install -D "$SCRIPT_DIR"/artifacts/001_vllm_mi250x.sh /opt/envs/vllm/lib/python3.12/site-packages/Magpie/scripts/benchmark/vllm_mi250x.sh

apply_patch patches/002_001_gfx90a_fp8_w8a8_bf16_emulation.patch
apply_patch patches/003_002_kernel_selection_invalidates_aot_cache.patch

apply_patch patches/004_001_gfx90a_fp8_w8a8_bf16_emulation.patch
apply_patch patches/005_002_kernel_selection_invalidates_aot_cache.patch

vllm serve $MODEL --language-model-only
