#!/usr/bin/env bash
# Auto-generated by hyperloom — enablement fix replay script.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
export MODEL=/mnt/stripe-3mix-3t2/models/ornith-ai/Ornith-1.5-35B-A3B
export TP=2
export MAX_MODEL_LEN=6144
export FRAMEWORK_ROOT=/opt/envs/vllm/lib/python3.12/site-packages

apply_patch() {
  local patch_file="$SCRIPT_DIR/$1"
  for lvl in 1 0 2 3 4 5 6 7 8; do
    if git -C "$FRAMEWORK_ROOT" apply --check -p"$lvl" "$patch_file" 2>/dev/null; then
      git -C "$FRAMEWORK_ROOT" apply -p"$lvl" "$patch_file"
      return 0
    fi
  done
  echo "ERROR: could not apply $patch_file at any strip level" >&2
  return 1
}

apply_patch patches/001_003_rocm_visible_devices_logical_repin.patch

vllm serve $MODEL
