#!/usr/bin/env bash
# Launch a Hyperloom optimization run for the agent ("vibe coding") lane:
# Ornith-1.5-397B-FP8 on 8x MI250X, single-stream decode speed at long context,
# concurrency envelope 16 (NOT 64).
#
# It carries the two fixes the previous session was missing (see README.md):
#   1. the patched FP8->BF16 dequant-emulation vLLM reaches the *benchmark
#      server*, via VLLM_BIN -> operator-owned wrapper (PYTHONPATH is blocked on
#      every untrusted channel, so it cannot travel in a KB row or --extra-env);
#   2. timeout_seconds 7200 -> 1800 in a private asset root, so grid admission
#      stops requiring 7800 s x 2 rounds and a normal budget can fund a baseline.
#
# Usage:  bash launch.sh [max_hours] [target_gain] [--dry-run]
set -euo pipefail

ROOT=/home/qiba/ROCm.AI/hyperloom
PRESET="$ROOT/presets/ornith-agent-longctx"
PATCH="$ROOT/patches/fp8-w8a8-emulation-gfx90a"
MODEL=/mnt/kioxia-cm6-3t8/ai/models/ornith-ai/Ornith-1.5-397B-FP8
CONTAINER="${CONTAINER:-hyperloom-srv}"

DRY=""
case "${3:-}" in --dry-run) DRY=1 ;; esac
MAX_HOURS="${1:-5}"
TARGET_GAIN="${2:-30}"
LOGDIR="$PRESET/logs"; mkdir -p "$LOGDIR"
STAMP=$(date -u +%Y%m%d_%H%M%S)
INNER="$LOGDIR/inner_$STAMP.sh"

[[ -x "$PATCH/bin/vllm-emulation" ]] || { echo "missing wrapper: $PATCH/bin/vllm-emulation"; exit 1; }
[[ -f "$PRESET/assetroot/assets/configs/baseline_vllm.yaml" ]] || { echo "missing preset asset root"; exit 1; }

cat > "$INNER" <<EOF
#!/usr/bin/env bash
# Generated by launch.sh at $STAMP -- the exact in-container launch.
set -euo pipefail
cd "$ROOT"
export USER_DATA_PATH="$ROOT/session"                 # else artefacts land in /workspace/hyperloom
export KNOWLEDGE_LOCAL_ROOT="$ROOT/kb"                # warm-start reads the workstation KB
export INFERENCE_OPTIMIZER_ASSET_ROOT="$PRESET/assetroot"   # timeout_seconds 1800 + lane defaults
export FRAMEWORK=vllm                                 # selects baseline_vllm.yaml + vllm_mi250x.sh
export VLLM_ROCM_USE_AITER=0                          # AITER is a dead route on gfx90a
export HSA_NO_SCRATCH_RECLAIM=1
# VLLM_ROCM_SPLITKV_PA=1: the wheel already contains a MI250X split-KV
# (flash-decoding) decode kernel, dispatched right before the serial 1-CTA path,
# OFF by default. Enabling it is worth x13 at 128k / x21.7 at 240k on this route.
# Not enabled here (pending round K2): VLLM_ROCM_SPLITKV_PA_MAX_Q=3 +
# VLLM_ROCM_SPLITKV_PA_MAX_SCRATCH_MIB=192, which are needed to stack it with MTP.
# max-model-len 262144 = the checkpoint's trained context. It fits ONE stream in
# today's 452,748-token KV pool; if config C shows that boot is not viable, fall
# back to 40960 (which also keeps --max-num-seqs 16 useful).

exec /opt/envs/vllm/bin/python3 -m hyperloom.inference_optimizer.cli --verbose optimize \\
  --model "$MODEL" \\
  --framework vllm --framework-version 0.28.0 --gpu-type mi250x --precision fp8 \\
  --tp 8 --ep 1 \\
  --conc 1 --isl 32768 --osl 1024 --max-model-len 262144 \\
  --max-hours "$MAX_HOURS" --target-gain "$TARGET_GAIN" \\
  --server-args '--language-model-only --max-num-seqs 16 --max-num-batched-tokens 8192 --enable-prefix-caching' \\
  --extra-env VLLM_BIN="$PATCH/bin/vllm-emulation" \\
  --extra-env VLLM_ROCM_SPLITKV_PA=1 \\
  --target-summary 'Agent (vibe-coding) lane on 8x MI250X: maximize SINGLE-STREAM decode tokens/s at 32k context with CONC=1 (hard envelope: 16 concurrent sessions). The engine is overhead-bound, not HBM- or FLOP-bound, so prefer levers that remove per-token launches and forward passes (MTP speculative decoding from the checkpoint's BF16 mtp layer, fused/grouped MoE GEMM, full-graph coverage) over aggregate-throughput tricks like deep batching. Do not trade per-stream latency for aggregate throughput.'
EOF
chmod +x "$INNER"

if [[ -n "$DRY" ]]; then
  echo "[dry-run] inner launch written to $INNER"; echo; cat "$INNER"; exit 0
fi

busy=$(rocm-smi --showmeminfo vram 2>/dev/null | awk -F: '/Used Memory/{gsub(/[^0-9]/,"",$2); if($2+0>300000000) c++} END{print c+0}')
[[ "$busy" == "0" ]] || { echo "[launch] $busy die(s) still busy -- free them first (inner script kept: $INNER)"; exit 1; }

echo "[launch] max_hours=$MAX_HOURS target_gain=$TARGET_GAIN inner=$INNER"
echo "[launch] log=$LOGDIR/run_$STAMP.log"
sudo -n docker exec "$CONTAINER" bash "$INNER" 2>&1 | tee "$LOGDIR/run_$STAMP.log"
