#!/usr/bin/env bash
# Generated by launch.sh at 20260916_011454 -- the exact in-container launch.
set -euo pipefail
cd "/home/qiba/ROCm.AI/hyperloom"
export USER_DATA_PATH="/home/qiba/ROCm.AI/hyperloom/session"                 # else artefacts land in /workspace/hyperloom
export KNOWLEDGE_LOCAL_ROOT="/home/qiba/ROCm.AI/hyperloom/kb"                # warm-start reads the workstation KB
export INFERENCE_OPTIMIZER_ASSET_ROOT="/home/qiba/ROCm.AI/hyperloom/presets/ornith-agent-longctx/assetroot"   # timeout_seconds 1800 + lane defaults
export FRAMEWORK=vllm                                 # selects baseline_vllm.yaml + vllm_mi250x.sh
export VLLM_ROCM_USE_AITER=0                          # AITER is a dead route on gfx90a
export HSA_NO_SCRATCH_RECLAIM=1

exec /opt/envs/vllm/bin/python3 -m hyperloom.inference_optimizer.cli --verbose optimize \
  --model "/mnt/kioxia-cm6-3t8/ai/models/ornith-ai/Ornith-1.5-397B-FP8" \
  --framework vllm --framework-version 0.28.0 --gpu-type mi250x --precision fp8 \
  --tp 8 --ep 1 \
  --conc 1 --isl 32768 --osl 1024 --max-model-len 40960 \
  --max-hours "5" --target-gain "30" \
  --server-args '--language-model-only --max-num-seqs 16 --max-num-batched-tokens 8192 --enable-prefix-caching' \
  --extra-env VLLM_BIN="/home/qiba/ROCm.AI/hyperloom/patches/fp8-w8a8-emulation-gfx90a/bin/vllm-emulation" \
  --target-summary 'Agent (vibe-coding) lane on 8x MI250X: maximize SINGLE-STREAM decode tokens/s at 32k context with CONC=1 (hard envelope: 16 concurrent sessions). The engine is overhead-bound, not HBM- or FLOP-bound, so prefer levers that remove per-token launches and forward passes (MTP speculative decoding from the checkpoint's BF16 mtp layer, fused/grouped MoE GEMM, full-graph coverage) over aggregate-throughput tricks like deep batching. Do not trade per-stream latency for aggregate throughput.'
