#!/usr/bin/env python3
"""Audit the mi250x-recipe-ops skill data against its authoritative recipe markdown.

Why this exists
---------------
The skill's `data/*.json` entries are **LLM-synthesised** from
`$AI/docs/recipes/**/*.md`: fields like `stack.notes`, `red_lines`,
`status_note` and `path_or_target` are prose that was written by reading the
markdown, not text a regular expression can lift out (verified empirically --
`rebuild`/`selfcheck` are condensed one-line commands, not raw code-block
lines). So the JSON must NOT be regenerated by a script: doing so would
overwrite hand-written synthesis with junk and silently drop fields.

What is actually missing is a **consistency gate**: when the markdown changes
and the JSON does not (the observed failure mode -- `data/*.json` still carries
`generated_at` from the last extraction), nothing notices. This script notices.

What it checks (all read-only)
------------------------------
1. every markdown file has a JSON entry with the same `id`, and vice versa;
2. frontmatter that maps verbatim to a JSON field agrees exactly
   (`status`, `verified`; `title_or_why` = `title` [+ " · "/"—" + `why`]);
3. every frontmatter `sources:` path exists on disk (catches renamed/deleted
   evidence a recipe still cites);
4. every frontmatter `consumers:` id resolves to a real arm in `data/arms.json`;
5. **claim drift**: for each JSON entry, which side mentions a topic keyword and
   which does not -- a keyword cited by the JSON but absent from the markdown is
   a field that was never written back into the authoritative source. Some of
   those are legitimately synthesised (by design), so the report separates them
   instead of failing.

Exit codes: 0 clean, 1 findings worth acting on, 2 unusable input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SKILL = Path("/home/qiba/ROCm.AI/local-skills/mi250x-recipe-ops")
AI = Path("/home/qiba/ai")
RECIPES = AI / "docs" / "recipes"
# 证据根不止一个：配方合法地引用 **ROCm.AI 仓**里的东西（hyperloom/reports、
# quark-int8、patches…）。第一版只认 AI 一个根，于是把 8121 引用的
# `hyperloom/reports/models/glm53-int4/*.md` 全报成「来源不存在」——三条误报。
REPO = SKILL.parent.parent          # /home/qiba/ROCm.AI
EVIDENCE_ROOTS = [AI, AI / "docs", REPO, REPO / "hyperloom"]

# JSON fields that are synthesised prose by design: a keyword living only here
# is normal, not drift. Everything else should trace back to the markdown.
SYNTHESISED = {
    "stack",
    "apply_verify_revert",
    "status_note",
    "path_or_target",
    "title_or_why",
    "rebuild",
    "selfcheck",
    "red_lines",
    "consumers",
    "kind",
    "id",
    "status",
    "verified",
}

# Topics worth flagging when the JSON knows about them but the markdown does
# not -- i.e. knowledge that has not been written back to the authoritative
# source. Keep this list small and high-signal.
TOPICS = {
    "aiter_jit_prebuilt": [
        r"AITER_JIT_DIR",
        r"预编译",
        r"jit/build",
        r"裸名",
        r"module_gemm_a8w8\.so",
    ],
    "gfx90a_code_object": [
        r"gfx90a\s*码对象",
        r"amdhsa--gfx90a",
        r"码对象",
    ],
    # 适用范围：JSON 里有 applies_to / effect_by_scope，而权威 markdown 一个字都没有
    # ⇒ 下次抽取必然丢。把它变成**看得见的漂移**，而不是隐形缺口。
    "scope_applicability": [
        r"applies_to",
        r"适用范围",
        r"适用域",
        r"effect_by_scope",
        r"consumed_by",
    ],
}



# ── 受控词表：markdown 侧的 applies_to 也要验 ────────────────────────────
# 解析器把 `applies_to:` 读成 ["axis=value", ...]（`- 轴=值` 列表写法），
# 所以这里按这个形状解析。多值用 `|` 分隔（如 `arch=qwen3_5|qwen4exp`）。
def _scope_spec():
    p = SKILL / "data" / "scope.json"
    if not p.is_file():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


SCOPE_SPEC = _scope_spec()


def validate_md_applies(applies_to, spec):
    """返回 [(轴=值, 问题)]。空 = 合规。spec 缺失或该配方没写 applies_to ⇒ 不判。"""
    if not applies_to or not spec:
        return []
    axes = spec.get("axes", {})
    presets = {k: v for k, v in spec.get("scope_presets", {}).items()
               if not k.startswith("_")}
    out = []
    items = applies_to if isinstance(applies_to, list) else [applies_to]
    for raw in items:
        s = str(raw).strip()
        if "=" not in s:
            out.append((s, "不是 `轴=值` 形状"))
            continue
        ax, _, val = s.partition("=")
        ax, val = ax.strip(), val.strip()
        if ax not in axes:
            out.append((s, f"轴名 {ax!r} 不在九轴里"))
            continue
        if val == "*" or "*" in val:
            continue                       # 通配 / glob
        if axes[ax].get("open"):
            continue                       # 开集轴（权重 id 等）不查词表
        vocab = set(axes[ax].get("vocab", {}))
        for one in [v.strip() for v in val.split("|") if v.strip()]:
            if one not in vocab:
                near = sorted(x for x in vocab if one.lower() in x.lower())[:3]
                out.append((s, f"值 {one!r} 不在 axes.{ax}.vocab（近似值 {near}）"))
    return out


def validate_md_preset(name, spec):
    if not name or not spec:
        return None
    presets = {k: v for k, v in spec.get("scope_presets", {}).items()
               if not k.startswith("_")}
    if name not in presets:
        return f"applies_preset {name!r} 不在 scope_presets 里"
    return None

def frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter scalars+lists, body). Handles `key: [a, b]` and `- item`."""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return {}, text
    raw, body = m.group(1), text[m.end():]
    fm: dict[str, object] = {}
    key = None
    for line in raw.splitlines():
        if re.match(r"^\s+-\s+", line):  # list item of the previous key
            if key:
                fm.setdefault(key, [])
                assert isinstance(fm[key], list)
                fm[key].append(re.sub(r"^\s*-\s+", "", line).strip())
            continue
        km = re.match(r"^([A-Za-z_][\w]*):\s*(.*)$", line)
        if not km:
            # 缩进续行：YAML 的多行标量/列表项折行。第一版直接 continue，
            # 于是把折行的尾巴（如 '8}.md'）当成独立来源 ⇒ 假阳性。
            #
            # 2026-09-21 修 IndexError：`key:` 后面直接跟一个**缩进续行**时，
            # `val == ""` 已把 fm[key] 置为**空列表**，再取 `[-1]` 就崩。
            # serving 目录下首次触发（此前只跑 environments|patches|knobs|ops）。
            if key and line.strip():
                cur = fm.get(key)
                if isinstance(cur, list):
                    if cur:
                        cur[-1] = f"{cur[-1]} {line.strip()}".strip()
                    else:
                        fm[key] = line.strip()   # 空列表 ⇒ 退化成标量，别丢内容
                elif isinstance(cur, str):
                    fm[key] = f"{cur} {line.strip()}".strip()
            continue
        key, val = km.group(1), km.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            fm[key] = [x.strip().strip('"\'') for x in val[1:-1].split(",") if x.strip()]
        elif val == "":
            fm[key] = []
        else:
            fm[key] = val.strip('"')
    return fm, body


def topic_hits(text: str) -> dict[str, int]:
    return {
        name: sum(1 for pat in pats if re.search(pat, text))
        for name, pats in TOPICS.items()
    }


def norm(s: str) -> str:
    """正常化：抽取时刻意去掉中文词间空格与 markdown 反引号，比较前要抹平，
    否则 'vLLM 0.28.0' vs 'vLLM0.28.0'、'`/opt/rocm-7.2.4`' vs '/opt/rocm-7.2.4'
    全是假阳性（第一版就是这么误报 11 条的）。"""
    s = re.sub(r"\s+", "", s or "")
    s = s.replace("`", "").replace("\u3000", "")
    s = s.replace("——", "-").replace("—", "-")
    return s


def drop_paths(s: str) -> str:
    """去掉长路径式 token（title 里常嵌 `@envs/xxx` 这类定位串）。"""
    return re.sub(r"\S*/\S*", "", norm(s))


def evidence_paths(raw: str) -> list[str]:
    """一个 sources 条目里可能用顿号/逗号列了多个文件（第一版整条当一个路径
    ⇒ 'xx.patch、yy.md5' 这种必然误报）。

    2026-09-21 两处修补（ops 目录首次被审计时暴露）：
      · 形如 `标签：/绝对/路径.py` 的条目：冒号前是人类可读的标签，不是路径
        ⇒ 先剥标签，否则整串被当路径。
      · 绝对路径（`/mnt/...`、`/home/...`）不该按"相对某个根"解析 ⇒ 直接判存在。
    """
    out = []
    for part in re.split(r"[、,，]", str(raw)):
        part = re.split(r"\s*(?:§|（|\()", part)[0].strip().rstrip("）) ")
        # 剥掉 `标签：` 前缀（标签里通常不含 '/'，出现 '/' 才可能是路径的一部分）
        m = re.match(r"^([^/：]{1,24})[：:]\s*(\S.*)$", part)
        if m:
            part = m.group(2).strip()
        if not part:
            continue
        if part.startswith("/"):
            if Path(part).exists():
                continue
            out.append(part)
            continue
        looks_like_file = part.endswith(
            (".md", ".py", ".sh", ".json", ".txt", ".patch", ".md5", ".hip"))
        is_glob = any(c in part for c in "*?{}[]")
        if not part.startswith(("CLAUDE", "http")) and looks_like_file and not is_glob:
            out.append(part)
    return out


def audit_scope() -> int:
    """校验适用范围（applies_to）—— 分层能不能用，取决于这一层的数据是否自洽。

    查四件事（只读）：
      1. `data/scope.json` 的九轴是否覆盖所有出现在 `applies_to` 里的键；
      2. 每个非 `*`/非 glob 的取值是否在对应轴的 vocab 里（词表外 = 拼错的轴值，
         这类错误最阴——它不会报错，只会让匹配永远返回「不适用」）；
      3. 每条条目（arms/environments/patches/knobs/ops）都有 `applies_to` 与 `tier`；
      4. `effect_by_scope` 的 `when` 用的键也在词表内。

    Exit: 0 clean, 1 findings, 2 unusable input.
    """
    spec_p = SKILL / "data" / "scope.json"
    if not spec_p.is_file():
        sys.exit(f"missing {spec_p}")
    spec = json.loads(spec_p.read_text(encoding="utf-8"))
    axes = set(spec["axes"])
    presets = {k: v for k, v in spec.get("scope_presets", {}).items()
               if not k.startswith("_")}
    vocab = {ax: set(d["vocab"]) for ax, d in spec["axes"].items()}
    # 开集轴：取值本身是开放集合（权重 id、镜像 sha、commit…），词表只举例不设限。
    # 不加这条，校验器会把每一条 model=HF-id 都当成"拼错的轴值"报出来。
    open_axes = {ax for ax, d in spec["axes"].items() if d.get("open")}

    findings: list[str] = []
    print(f"data/scope.json  schema v{spec.get('schema_version')}  "
          f"轴 {len(axes)}  词表项 {sum(len(v) for v in vocab.values())}  "
          f"preset {len(presets)}\n")

    files = [
        ("arms.json", "arms", "recipe_id"),
        ("environments.json", "environments", "id"),
        ("patches.json", "patches", "id"),
        ("knobs.json", "knobs", "id"),
        ("ops.json", "ops", "id"),
    ]
    n_items = 0
    used_values: dict[str, set] = {ax: set() for ax in axes}

    def check_block(where: str, block: dict, allow_preset: bool) -> None:
        if allow_preset and "preset" in block:
            p = block["preset"]
            if p not in presets:
                findings.append(f"[未知 preset] {where}: {p!r} 不在 scope_presets 里")
            else:
                for k, v in presets[p].items():
                    if k != "tier":
                        used_values.setdefault(k, set()).update(
                            [] if v == "*" else (v if isinstance(v, list) else [v]))
        for k, v in block.items():
            if k in ("preset", "tier"):
                continue
            if k not in axes:
                findings.append(f"[轴不在词表] {where}: 键 {k!r} 不是九轴之一")
                continue
            vals = v if isinstance(v, list) else [v]
            for val in vals:
                used_values[k].add(val)
                if val == "*" or "*" in str(val):
                    continue
                if k in open_axes:
                    continue
                if val not in vocab[k]:
                    findings.append(
                        f"[轴值不在词表] {where}: {k}={val!r} 不在 scope.json > "
                        f"axes.{k}.vocab（词表外取值会让匹配永远返回「不适用」）")

    for fname, key, idf in files:
        p = SKILL / "data" / fname
        j = json.loads(p.read_text(encoding="utf-8"))
        for e in j[key]:
            n_items += 1
            i = e.get(idf) or e.get("id") or "?"
            if "applies_to" not in e:
                findings.append(f"[缺 applies_to] {fname} :: {i}")
                continue
            blk = e["applies_to"]
            # tier 可以由 preset 提供 ⇒ 先展开再判，别只看字面
            eff_tier = blk.get("tier") or (
                presets.get(blk.get("preset"), {}).get("tier") if "preset" in blk else None)
            if not eff_tier:
                findings.append(
                    f"[缺 tier] {fname} :: {i}（applies_to 或它引用的 preset 里必须有 T0–T3）")
            elif eff_tier not in spec["tiers"]:
                findings.append(f"[tier 非法] {fname} :: {i}: {eff_tier!r}")
            check_block(f"{fname}::{i}", blk, allow_preset=True)
            for eb in e.get("effect_by_scope", []) or []:
                check_block(f"{fname}::{i}::effect_by_scope", eb.get("when") or {},
                            allow_preset=False)

    print(f"条目 {n_items} 条；各轴被用到的取值：")
    for ax in spec["axes"]:
        vals = sorted(v for v in used_values.get(ax, set()) if v != "*")
        print(f"  {ax:9s} 词表 {len(vocab[ax]):2d}  实际用到 {len(vals):2d}"
              f"{'  ← 词表里有但没人用的: ' + str(sorted(vocab[ax] - set(vals))) if vocab[ax] - set(vals) else ''}")

    if findings:
        print(f"\n── 适用范围发现（{len(findings)}）──")
        for f in findings:
            print("  " + f)
        return 1
    print("\n适用范围：无发现 ✓")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument(
        "--dir",
        default="environments",
        help="recipes subdir to audit (environments|patches|knobs|ops|serving)",
    )
    ap.add_argument(
        "--scope",
        action="store_true",
        help="只跑适用范围（applies_to）校验：键在词表内、值在 vocab 内或是 glob、"
             "每条条目都有 applies_to 与 tier",
    )
    args = ap.parse_args()

    # ---- load skill data ----
    def load(name: str):
        p = SKILL / "data" / name
        if not p.is_file():
            sys.exit(f"missing skill data: {p}")
        return json.loads(p.read_text(encoding="utf-8"))

    # `idf` = 该数据集里主键的字段名。arms.json 用的是 `recipe_id`，
    # 第一版这里写死 `e["id"]` 并对 arms 用 `a.get("id")`，于是
    # `arms` 集合恒为 {None} ⇒ 「consumers 是否解析到真实臂」这条检查
    # 从来没生效过（只 warn 且只在 --verbose 下打）。见 2026-09-21 修复。
    dsets = {
        "environments": ("environments.json", "environments", "id"),
        "patches": ("patches.json", "patches", "id"),
        "knobs": ("knobs.json", "knobs", "id"),
        "ops": ("ops.json", "ops", "id"),
        "serving": ("arms.json", "arms", "recipe_id"),
    }

    if args.scope:
        return audit_scope()

    if args.dir not in dsets:
        sys.exit(f"--dir must be one of {sorted(dsets)}")
    dfile, dkey, idf = dsets[args.dir]
    entries = {e[idf]: e for e in load(dfile)[dkey]}
    # 全种类 id 全集：consumers / scope 都要在它里面解析。
    all_ids: set[str] = set()
    for _f, _k, _i in dsets.values():
        all_ids |= {e[_i] for e in load(_f)[_k]}
    arms = {a["recipe_id"] for a in load("arms.json")["arms"]}
    gen = load(dfile).get("generated_at", "?")

    findings: list[str] = []   # ERROR：真不一致
    infos: list[str] = []      # INFO：覆盖缺口，不作为失败
    print(f"data/{dfile}  generated_at={gen}  条目 {len(entries)}")
    print(f"权威目录 {RECIPES / args.dir}\n")

    mds = sorted((RECIPES / args.dir).glob("*.md"))
    if not mds:
        sys.exit(f"no markdown under {RECIPES / args.dir}")
    seen = set()
    drift_rows = []

    for md_path in mds:
        text = md_path.read_text(encoding="utf-8")
        fm, body = frontmatter(text)
        mid = fm.get("id") or md_path.stem
        seen.add(mid)

        # 6) 权威 markdown 自己的 `applies_to` 必须在词表内。
        #    只验 JSON 不够：JSON 是合成物、会被重写，markdown 才是权威源。
        #    2026-09-21 实测漏网——并发新增的配方写了 `engine=vllm-master`、`arch=Qwen4Exp`
        #    （词表里是 `vllm-master@8a728663c`、`qwen4exp`）。轴名对、值拼错这类错
        #    **不会报错，只会让匹配永远返回「不适用」**，正是受控词表要防的东西。
        for rel, bad in validate_md_applies(fm.get("applies_to"), SCOPE_SPEC):
            if bad:
                findings.append(f"[md applies_to 越表] {mid}: {rel} → {bad}")
        err = validate_md_preset(fm.get("applies_preset"), SCOPE_SPEC)
        if err:
            findings.append(f"[md applies_preset] {mid}: {err}")

        if mid not in entries:
            infos.append(
                f"[覆盖缺口] {md_path.name}: data/{dfile} 里没有 id={mid}"
                "（如该配方从未被抽取，JSON 只是子集则属预期）"
            )
            continue
        e = entries[mid]

        # 2) verbatim-mappable frontmatter
        for jkey, fkey in (("status", "status"), ("verified", "verified")):
            if fkey in fm and norm(str(e.get(jkey))) != norm(str(fm[fkey])):
                findings.append(
                    f"[frontmatter 不一致] {mid}.{jkey}: json={e.get(jkey)!r} md={fm[fkey]!r}"
                )
        # title_or_why: 抽取时把 title 与 why 拼接成一个字段，且 field 里可能
        # 嵌了 title 没有的路径定位串 ⇒ 只要求 title 去路径后**被包含**。
        if "title" in fm:
            t = drop_paths(str(fm["title"]))
            j = drop_paths(str(e.get("title_or_why", "")))
            if t and t not in j and j and not j.startswith(t[:24]):
                findings.append(
                    f"[title_or_why 漂移] {mid}: json={j[:44]!r} 与 md title={t[:44]!r} 不相容"
                )

        # 3) sources: frontmatter 里可能一行列多个文件
        for s in fm.get("sources", []) or []:
            for rel in evidence_paths(str(s)):
                if not any((root / rel).exists() for root in EVIDENCE_ROOTS):
                    roots = "、".join(str(r) for r in EVIDENCE_ROOTS)
                    findings.append(
                        f"[来源不存在] {mid}: sources 里的 {rel!r} 在下列根下都找不到：{roots}"
                    )

        # 4) consumers 必须解析到**某个**配方 id。
        #    2026-09-21 更正：第一版把 consumers 只当"臂 id"，于是
        #    `rocm724`（环境）的 consumers=[vllm_0.28.0_rocm72, …]、
        #    `hipais-shim`（补丁）的 consumers=[ais-hipfile-load]（knob）
        #    全被报成悬空——它们其实都对。consumers 的语义是"谁消费它"，
        #    消费方可以是环境/补丁/开关/臂/操作，不限种类。
        #    同一次修复还去掉了 `a.get("id")`（arms.json 的主键叫 recipe_id，
        #    写错导致 arms 集合恒为 {None}，这条检查此前从未真正生效）。
        for c in fm.get("consumers", []) or []:
            head = re.split(r"[（(]", str(c))[0].strip().strip('"\'')
            if head and head not in all_ids and re.match(r"^[a-z0-9][a-z0-9._\-]{5,}$", head):
                findings.append(
                    f"[consumers 悬空] {mid}: consumer {head!r} 不是任何配方的 id"
                    f"（臂/环境/补丁/开关/操作都算）"
                )
        # knob 的 `scope:` 是**溯源**（skill JSON 里叫 `consumed_by`），**不是**
        # 适用判定：实测它混过臂 id、knob id、散文（"离线加载（唯一正解入口 …）"）
        # 与带尾注的**否定**消费者（"8111-…（不接投机，仅为记录）"）。
        # 这里只对"看起来像 id 却解析不到"的报；散文留给人工。
        # 适用判定在 `--scope`（applies_to）与 scripts/scope_match.py。
        for c in fm.get("scope", []) or []:
            head = re.split(r"[（(]", str(c))[0].strip()
            if head and head not in all_ids and re.match(r"^[a-z0-9][a-z0-9._\-]{5,}$", head):
                findings.append(
                    f"[scope 悬空] {mid}: scope 里的 {head!r} 不是任何配方的 id"
                )

        # 5) topic drift between JSON entry and markdown
        jh, mh = topic_hits(json.dumps(e, ensure_ascii=False)), topic_hits(text)
        for topic in TOPICS:
            if jh[topic] and not mh[topic]:
                drift_rows.append((mid, topic))

    for mid in sorted(set(entries) - seen):
        findings.append(f"[孤儿条目] data/{dfile} 有 {mid}，但 {args.dir}/ 下没有对应 md")

    # ---------------- report ----------------
    # 主题漂移独立输出：即使结构无发现，这条也常是最有价值的信号。
    print("── 主题漂移：JSON 知道、但 md（权威源）没写 ──")
    if drift_rows:
        for mid, topic in drift_rows:
            print(f"  {mid:34s} {topic}")
        print(
            "  说明：若属综合字段（stack/red_lines/status_note/path_or_target）属设计内；\n"
            "        若是**事实**（某个 .so 的存废、某个开关的取值），应回写 md，否则下次抽取会丢。"
        )
    else:
        print("  无 ✓")

    if infos:
        print("\n── 覆盖缺口（JSON 是 md 的子集，非失败）──")
        for i in infos:
            print("  " + i)

    if findings:
        print("\n── 结构一致性发现 ──")
        for f in findings:
            print("  " + f)
        print(f"\n共 {len(findings)} 条不一致。")
        return 1

    print("\n结构一致性：无发现 ✓")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
